# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  use_frameworks!

target 'github_search_app' do
    pod 'SnapKit'
    pod 'RxSwift'
    pod 'AlamofireImage'
    pod 'Moya'
    pod 'Moya-ObjectMapper/RxSwift'
    pod 'RxCocoa'
end